### PR TITLE
Added ROS Standard SensorMsgs:

### PR DESCRIPTION
**Pull request by unl0ck**
- Header
- TimeStamp

maybe it is useful, 
added first Messages from Standard SensorMsgs.
https://github.com/ros/common_msgs/tree/jade-devel/sensor_msgs/msg

### CODE REVIEW

**Comment by wesgood** [comment]
These messages are actually included in the original package, with names TimeMessage and HeaderMessage. Did you want to add anything specifically to those message types?

**Comment by unl0ck** [comment]
for CompressedImage I need an TimeStamp with Int.
I tested with the TimeMessage and it doesn't work, show only 0.
but it is okay =) no problem, maybe later I will add more sensorMessages with other, where are hopefully not exist =).
sorry.

**Comment by wesgood** [comment]
With int, that's interesting. Could the full TimeMessage be a different type? I tried to follow the ROS wiki best as possible

**Comment by unl0ck** [comment]
I am Working on an App to Show Camera pictures. 
I am Unsing an Raspberry Pi and this Node

https://github.com/UbiquityRobotics/raspicam_node

But they using Standard msgs.
Currently i get no Image Data ... 


Simon Helming

**Pull request closed without merging**
